name: CI
on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
         run: make install
      - name: Lint with Pylint
         run: make lint
      - name: Test with Pytest
         run: make test
      - name: Format code with Python black
         run: make format